spring.application.name=trafficfines
debug=true
debug=true

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/trafficfines_db
spring.datasource.username=postgres
spring.datasource.password=pasan

# Hibernate — creates tables automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Execute data.sql after Hibernate creates tables
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JWT Configuration
app.jwtSecret=TrafficFinesSystemSecretKey12345678901234567890
app.jwtExpirationMs=86400000

logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG
