spring.application.name=trafficfines

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/trafficfines_db
spring.datasource.username=postgres
spring.datasource.password=pasan
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
app.jwtSecret=TrafficFinesSystemSecretKey12345678901234567890
app.jwtExpirationMs=86400000
