package com.slpolice.trafficfines.fine.entity;

import com.slpolice.trafficfines.auth.entity.User;
import com.slpolice.trafficfines.payment.entity.Payment;
import com.slpolice.trafficfines.shared.entity.BaseEntity;
import jakarta.persistence.*;
import lombok.*;

/**
 * Represents a traffic fine issued by a police officer to a driver.
 * Maps to the FINES table as defined in the ER diagram.
 *
 * Key design decision: reference_number is a unique alphanumeric code
 * printed on the physical fine sheet (e.g., TF-2026-WP-00001).
 */
@Entity
@EqualsAndHashCode(callSuper = false)
@Table(name = "fines", indexes = {
        // Index on reference_number for fast lookup (NFR: API response < 500ms)
        @Index(name = "idx_fines_reference_number", columnList = "reference_number"),
        // Index on category_id for reporting queries
        @Index(name = "idx_fines_category_id", columnList = "category_id")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Fine extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique reference number printed on the physical fine sheet.
     * e.g., TF-2026-WP-00001
     * Generated by ReferenceNumberGenerator utility.
     */
    @Column(name = "reference_number", nullable = false, unique = true, length = 30)
    private String referenceNumber;

    /**
     * The officer who issued this fine (FK to USERS).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "officer_id", nullable = false)
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private User officer;

    /**
     * The category of violation (FK to FINE_CATEGORIES).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private FineCategory category;

    @Column(name = "driver_license_no", nullable = false, length = 20)
    private String driverLicenseNo;

    @Column(name = "driver_name", nullable = false)
    private String driverName;

    @Column(name = "vehicle_number", nullable = false, length = 15)
    private String vehicleNumber;

    @Column(name = "district", nullable = false, length = 50)
    private String district;

    @Column(name = "location")
    private String location;

    /**
     * Current status of the fine: PENDING | PAID | EXPIRED
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 10)
    @Builder.Default
    private FineStatus status = FineStatus.PENDING;

    /**
     * The payment associated with this fine (one-to-one, optional until paid).
     */
    @OneToOne(mappedBy = "fine", fetch = FetchType.LAZY)
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private Payment payment;
}
